SOMEGROUP:
    SOMESTRING: xyz
    SOMEDICT:
        v1: k1
        v2: k2
    SOMELIST:
        - v1
        - v2

DEFAULT:
    LOGGER_LEVEL: INFO

MYSQL:
    IP: 172.17.0.2
    DATABASE: doppler_muslumovo
    USER: disp

COMPUTE:
    OBJECTS:
        1-9СП:
            SELF_TS: 
                1-9СП(к): 1
            CONSTRAIN:
                K9+: 1
                K3+: 1
                K1+: 1
            SIBLING_TS:
                IIАП: 1
                НАП: 1
            LENGTH: 25

        НАП:
            SELF_TS: 
                НАП(к): 1
            CONSTRAIN:
            SIBLING_TS:
                1-9СП(к): 1
                Н1ИП: 0
            LENGTH: 125
