SOMEGROUP:
    SOMESTRING: xyz
    SOMEDICT:
        v1: k1
        v2: k2
    SOMELIST:
        - v1
        - v2

MAIN:
    LOG_LEVEL: INFO  #[DEBUG|INFO|WARNING|ERROR|CRITICAL]
    MYSQL:
        IP: 172.17.0.2
        DATABASE: doppler_muslumovo
        USER: disp

COMPUTE:
    ANOMALY_SPEED: 150
    LOG_FILE: "anomaly_log.txt"
    OBJECTS:
        1-9СП(1+,3+,9+):
            SELF_TS: 
                1-9СП(к): 1
            CONSTRAIN:
                К9+: 1
                К35+: 1
                К1+: 1
            SIBLING_TS:
                2АП(к): 1
                НАП(к): 1
            LENGTH: 146

        1-9СП(1+,3+,9-):
            SELF_TS: 
                1-9СП(к): 1
            CONSTRAIN:
                К9-: 1
                К35+: 1
                К1+: 1
            SIBLING_TS:
                3АП(к): 1
                НАП(к): 1
            LENGTH: 146

        1-9СП(1+,3-):
            SELF_TS: 
                1-9СП(к): 1
            CONSTRAIN:
                К35-: 1
                К1+: 1
            SIBLING_TS:
                5-13СП(к): 1
                НАП(к): 1
            LENGTH: 108

        1-9СП(1-):
            SELF_TS: 
                1-9СП(к): 1
            CONSTRAIN:
                К1-: 1
            SIBLING_TS:
                7СП(к): 1
                НАП(к): 1
            LENGTH: 39

        4СП(4+):
            SELF_TS: 
                4СП(к): 1
            CONSTRAIN:
                К24+: 1
            SIBLING_TS:
                Ч1УП: 0
                6-14СП(к): 1
            LENGTH: 332

        НАП:
            SELF_TS: 
                НАП(к): 1
            CONSTRAIN:
            SIBLING_TS:
                1-9СП(к): 1
                Н1ИП: 0
            LENGTH: 376

        ЧДП:
            SELF_TS: 
                ЧДП(к): 1
            CONSTRAIN:
            SIBLING_TS:
                2-8СП(к): 1
                ЧД1УП: 0
            LENGTH: 223

