SOMEGROUP:
    SOMESTRING: xyz
    SOMEDICT:
        v1: k1
        v2: k2
    SOMELIST:
        - v1
        - v2

MAIN:
    LOG_LEVEL: INFO  #[DEBUG|INFO|WARNING|ERROR|CRITICAL]
    MYSQL:
        IP: 172.17.0.2
        DATABASE: doppler_muslumovo
        USER: disp

COMPUTE:
    OBJECTS:
        1-9СП(1+,3+,9+):
            SELF_TS: 
                1-9СП(к): 1
            CONSTRAIN:
                К9+: 1
                К35+: 1
                К1+: 1
            SIBLING_TS:
                2АП(к): 1
                НАП(к): 1
            LENGTH: 1444

        НАП:
            SELF_TS: 
                НАП(к): 1
            CONSTRAIN:
            SIBLING_TS:
                1-9СП(к): 1
                Н1И2П: 0
            LENGTH: 125
