MAIN:
    LOG_LEVEL: INFO  #[DEBUG|INFO|WARNING|ERROR|CRITICAL]
    MYSQL:
        IP: 172.17.0.2
        DATABASE: doppler_muslumovo
        USER: disp

COMPUTE:
    ANOMALY_SPEED: 140
    LOG_FILE: "anomaly_log.txt"     #пока не используется
    OBJECTS:
        на_2П:
            SELF_TS: 
                НАП(к): 1
                Н1ИП: 0
            CONSTRAIN:
                К9+: 1
                К35+: 1
                К1+: 1
            SIBLING_TS:
                1-9СП(к): 1
                Н2ИП: 0
            LENGTH: 
                НАП(к): 376
                Н1ИП: 1000
            MOVE_TO: 1-9СП(к)
            SPEED_MIN_LIMIT: 20


