MAIN:
    LOG_LEVEL: INFO  #[DEBUG|INFO|WARNING|ERROR|CRITICAL]
    MYSQL:
        IP: 172.17.0.2
        DATABASE: doppler_muslumovo
        USER: disp

COMPUTE:
    ANOMALY_SPEED: 140
    LOG_FILE: "anomaly_log.txt"     #пока не используется
    OBJECTS:
        ЧД_пропуск_по_2П:
            SELF_TS: 
                ЧДП(к): 1
                ЧД1УП: 0
            CONSTRAIN:
                К24-: 1
                К68+: 1
                Ч2(з): 1
            SIBLING_TS:
                ЧДП(к):
                    2-8СП(к): 1
                    ЧД1УП: 0
                ЧД1УП:
                    ЧДП(к): 1
                    ЧД2УП: 0
            LENGTH: 
                ЧДП(к): 223
                ЧД1УП: 1000
            MOVE_TO:
                ЧДП(к): 2-8СП(к)
                ЧД1УП: ЧДП(к)
            SPEED_MIN_LIMIT: 20

        ЧД_останов_по_2П:
            SELF_TS: 
                ЧДП(к): 1
                ЧД1УП: 0
            CONSTRAIN:
                К24-: 1
                К68+: 1
                Ч2(з): 0
            SIBLING_TS:
                ЧДП(к):
                    2-8СП(к): 1
                    ЧД1УП: 0
                ЧД1УП:
                    ЧДП(к): 1
                    ЧД2УП: 0
            LENGTH: 
                ЧДП(к): 223
                ЧД1УП: 1000
            MOVE_TO:
                ЧДП(к): 2-8СП(к)
                ЧД1УП: ЧДП(к)
            SPEED_MIN_LIMIT: 20

