MAIN:
    LOG_LEVEL: INFO  #[DEBUG|INFO|WARNING|ERROR|CRITICAL]
    MYSQL:
        IP: 172.17.0.2
        DATABASE: doppler_muslumovo
        USER: disp

COMPUTE:
    ANOMALY_SPEED: 140
    LOG_FILE: "anomaly_log.txt"     #пока не используется
    OBJECTS:
        Н_на_2П:
            SELF_TS: 
                НАП(к): 1
                Н1ИП: 0
            CONSTRAIN:
                К9+: 1
                К35+: 1
                К1+: 1
            SIBLING_TS:
                НАП(к):
                    1-9СП(к): 1
                    Н1ИП: 0
                Н1ИП:
                    НАП(к): 1
                    Н2ИП: 0
            LENGTH: 
                НАП(к): 376
                Н1ИП: 1000
            MOVE_TO:
                НАП(к): 1-9СП(к)
                Н1ИП: НАП(к)
            SPEED_MIN_LIMIT: 20

        Н_на_3П:
            SELF_TS: 
                НАП(к): 1
                Н1ИП: 0
            CONSTRAIN:
                К9-: 1
                К35+: 1
                К1+: 1
            SIBLING_TS:
                НАП(к):
                    1-9СП(к): 1
                    Н1ИП: 0
                Н1ИП:
                    НАП(к): 1
                    Н2ИП: 0
            LENGTH: 
                НАП(к): 376
                Н1ИП: 1000
            MOVE_TO:
                НАП(к): 1-9СП(к)
                Н1ИП: НАП(к)
            SPEED_MIN_LIMIT: 20

        Ч_пропуск_по_2П:
            SELF_TS: 
                4СП(к): 1
                Ч1УП: 0
            CONSTRAIN:
                К24+: 1
                К68+: 1
                Ч2(з): 1
            SIBLING_TS:
                4СП(к):
                    6-14СП(к): 1
                    Ч1УП: 0
                Ч1УП:
                    4СП(к): 1
                    Ч2УП: 0
            LENGTH: 
                4СП(к): 332
                Ч1УП: 1000
            MOVE_TO:
                4СП(к): 6-14СП(к)
                Ч1УП: 4СП(к)
            SPEED_MIN_LIMIT: 20

        Ч_останов_на_2П:
            SELF_TS: 
                4СП(к): 1
                Ч1УП: 0
            CONSTRAIN:
                К24+: 1
                К68+: 1
                Ч2(з): 0
            SIBLING_TS:
                4СП(к):
                    6-14СП(к): 1
                    Ч1УП: 0
                Ч1УП:
                    4СП(к): 1
                    Ч2УП: 0
            LENGTH: 
                4СП(к): 332
                Ч1УП: 1000
            MOVE_TO:
                4СП(к): 6-14СП(к)
                Ч1УП: 4СП(к)
            SPEED_MIN_LIMIT: 20

        Ч_пропуск_по_3П:
            SELF_TS: 
                4СП(к): 1
                Ч1УП: 0
            CONSTRAIN:
                К24+: 1
                К68-: 1
                Ч3(з): 1
            SIBLING_TS:
                4СП(к):
                    6-14СП(к): 1
                    Ч1УП: 0
                Ч1УП:
                    4СП(к): 1
                    Ч2УП: 0
            LENGTH: 
                4СП(к): 332
                Ч1УП: 1000
            MOVE_TO:
                4СП(к): 6-14СП(к)
                Ч1УП: 4СП(к)
            SPEED_MIN_LIMIT: 20

        Ч_останов_на_3П:
            SELF_TS: 
                4СП(к): 1
                Ч1УП: 0
            CONSTRAIN:
                К24+: 1
                К68-: 1
                Ч3(з): 0
            SIBLING_TS:
                4СП(к):
                    6-14СП(к): 1
                    Ч1УП: 0
                Ч1УП:
                    4СП(к): 1
                    Ч2УП: 0
            LENGTH: 
                4СП(к): 332
                Ч1УП: 1000
            MOVE_TO:
                4СП(к): 6-14СП(к)
                Ч1УП: 4СП(к)
            SPEED_MIN_LIMIT: 20

        ЧД_пропуск_по_3П:
            SELF_TS: 
                ЧДП(к): 1
                ЧД1УП: 0
            CONSTRAIN:
                К24+: 1
                К68+: 1
                Ч3(з): 1
            SIBLING_TS:
                ЧДП(к):
                    2-8СП(к): 1
                    ЧД1УП: 0
                ЧД1УП:
                    ЧДП(к): 1
                    ЧД2УП: 0
            LENGTH: 
                ЧДП(к): 223
                ЧД1УП: 1000
            MOVE_TO:
                ЧДП(к): 2-8СП(к)
                ЧД1УП: ЧДП(к)
            SPEED_MIN_LIMIT: 20

        ЧД_останов_по_3П:
            SELF_TS: 
                ЧДП(к): 1
                ЧД1УП: 0
            CONSTRAIN:
                К24+: 1
                К68+: 1
                Ч3(з): 0
            SIBLING_TS:
                ЧДП(к):
                    2-8СП(к): 1
                    ЧД1УП: 0
                ЧД1УП:
                    ЧДП(к): 1
                    ЧД2УП: 0
            LENGTH: 
                ЧДП(к): 223
                ЧД1УП: 1000
            MOVE_TO:
                ЧДП(к): 2-8СП(к)
                ЧД1УП: ЧДП(к)
            SPEED_MIN_LIMIT: 20

        ЧД_пропуск_по_2П:
            SELF_TS: 
                ЧДП(к): 1
                ЧД1УП: 0
            CONSTRAIN:
                К24-: 1
                К68+: 1
                Ч2(з): 1
            SIBLING_TS:
                ЧДП(к):
                    2-8СП(к): 1
                    ЧД1УП: 0
                ЧД1УП:
                    ЧДП(к): 1
                    ЧД2УП: 0
            LENGTH: 
                ЧДП(к): 223
                ЧД1УП: 1000
            MOVE_TO:
                ЧДП(к): 2-8СП(к)
                ЧД1УП: ЧДП(к)
            SPEED_MIN_LIMIT: 20

        ЧД_останов_по_2П:
            SELF_TS: 
                ЧДП(к): 1
                ЧД1УП: 0
            CONSTRAIN:
                К24-: 1
                К68+: 1
                Ч2(з): 0
            SIBLING_TS:
                ЧДП(к):
                    2-8СП(к): 1
                    ЧД1УП: 0
                ЧД1УП:
                    ЧДП(к): 1
                    ЧД2УП: 0
            LENGTH: 
                ЧДП(к): 223
                ЧД1УП: 1000
            MOVE_TO:
                ЧДП(к): 2-8СП(к)
                ЧД1УП: ЧДП(к)
            SPEED_MIN_LIMIT: 20
