
DEFAULT:
    LOGGER_LEVEL: INFO


MYSQL:
    IP: 172.17.0.2
    DATABASE: doppler_muslumovo
    USER: disp

STAGE1:
    ENTRY_TS: Ч(з),Н(з),ЧД(з)
    RCIRC_TS: НАП(к),НАП(б),1-9СП(к),1-9СП(б),5-13СП(к),5-13СП(б),7СП(к),7СП(б),15-17СП(к),15-17СП(б),ЧДП(к),ЧДП(б),2-8СП(к),2-8СП(б),4СП(к),4СП(б),6-14СП(к),6-14СП(б),10СП(к),10СП(б),12-24СП(к),12-24СП(б),16-20СП(к),16-20СП(б),18СП(к),18СП(б),22СП(к),22СП(б)
    SAIL_TS: Н1(з),Н1(б),Н2(з),Н2(б),Н3(з),Н3(б),Н4(з),Н4(б),Н6(з),Н6(б), Ч1(з),Ч1(б),Ч2(з),Ч2(б),Ч3(з),Ч3(б),Ч4(з),Ч4(б),Ч6(з),Ч6(б)
    ALGO: describe

STAGE2:
    RCIRC_TS_MASK: sds