
MAIN:
    LOG_LEVEL: INFO  #[DEBUG|INFO|WARNING|ERROR|CRITICAL]
    MYSQL:
        IP: 172.17.0.2
        DATABASE: doppler_kolcovo
        USER: disp


COMPUTE:
    OBJECTS:
        1АП:
            SELF_TS:    #имя сигнала замыкания в маршруте ":" состояние когда элемента РАЗмыкается (УП-0, СП-1)
                1АП(б): 0   

        3СП:
            SELF_TS:
                3СП(б): 1

        5-7СП:
            SELF_TS:
                5-7СП(б): 1

        7СП:
            SELF_TS:
                7СП(б): 1

        11СП:
            SELF_TS:
                11СП(б): 1

        2АП:
            SELF_TS:
                ЧДП(б): 0

        1СП:
            SELF_TS:
                1СП(б): 1

        9СП:
            SELF_TS:
                9СП(б): 1

        13-15СП:
            SELF_TS:
                13-15СП(б): 1

        17СП:
            SELF_TS:
                17СП(б): 1

        19-25СП:
            SELF_TS:
                19-25СП(б): 1

        21-27СП:
            SELF_TS:
                21-27СП(б): 1

        29СП:
            SELF_TS:
                29СП(б): 1

        НМП:
            SELF_TS:
                НМП(б): 0

        35-37СП:
            SELF_TS:
                35-37СП(б): 1

        39-41СП:
            SELF_TS:
                39-41СП(б): 1

        НкБП:
            SELF_TS:
                НкБП(б): 0

        НкАП:
            SELF_TS:
                НкАП(б): 0

        ЧДП:
            SELF_TS:
                ЧДП(б): 0

        2СП:
            SELF_TS:
                2СП(б): 1

        8СП:
            SELF_TS:
                8СП(б): 1

        14-34СП:
            SELF_TS:
                14-34СП(б): 1

        16-18СП:
            SELF_TS:
                16-18СП(б): 1

        24-26СП:
            SELF_TS:
                24-26СП(б): 1

        ЧГП:
            SELF_TS:
                ЧГП(б): 0

        4СП:
            SELF_TS:
                4СП(б): 1

        6-12СП:
            SELF_TS:
                6-12СП(б): 1

        30-36СП:
            SELF_TS:
                30-36СП(б): 1

        10-32СП:
            SELF_TS:
                10-32СП(б): 1

        28СП:
            SELF_TS:
                28СП(б): 1

        20-38СП:
            SELF_TS:
                20-38СП(б): 1


